default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: insta

test:
  <<: *default
  database: insta_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
